### ISSUE TITLE
provider name and version not parsed correctly when any part of version more than 1 digit

### ISSUE THREAD

**Issue by christi3k** [dikhan/terraform-provider-openapi#172]
## Describe the bug

When installing the plugin with version information appended to the file per [terraform documentation](https://www.terraform.io/docs/configuration/providers.html#plugin-names-and-versions), the provider name and version are not parsed correctly when any part of the version suffix is more than one digit.

## To Reproduce

- macOS
- terraform v0.12.12
- openapi plugin v0.20.0

1. `wget https://github.com/dikhan/terraform-provider-openapi/releases/download/v0.20.0/terraform-provider-openapi_0.20.0_darwin_amd64.tar.gz`
2. `tar -xzvf terraform-provider-openapi_0.20.0_darwin_amd64.tar.gz`
3. `cp terraform-provider-openapi_v0.20.0 ~/.terraform.d/plugins/darwin_amd64/`
4. run `TF_LOG=DEBUG terraform init` and `TF_LOG=DEBUG terraform plan` with some terraform configuration that uses this provider.

In the logs for `terraform plan`, you should see something like this error:

```
[ERROR] There was an error when getting the provider's     name fomr the binary '/Users/chkoehle/.terraform.d/plugins/darwin_amd64/terraform-provider-slvm_v0.20.0': provider binary name (/Users/chkoehle/.           terraform.d/plugins/darwin_amd64/terraform-provider-slvm_v0.20.0) does not match terraform naming convention 'terraform-provider-{name}', please rename     the provider binary
```

## Expected behaviour

No error to be reported during `terraform plan`.

### Checklist

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [ ] I have added a corresponding label (feature request/bug/etc) to the issue (right side menu)
- [ ] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)

**Comment by dikhan** [comment]
Thanks @christi3k !

Just merged a fix for that. Will be releasing a new version shortly.
