### ISSUE TITLE
Open api plugin issue

### ISSUE THREAD

**Issue by Grasume** [dikhan/terraform-provider-openapi#263]
## Describe the bug
PS C:\Users\...\AppData\Roaming\terraform.d\plugins> .\terraform-provider-openapi.exe
2020/08/10 16:00:02 Running OpenAPI Terraform Provider v0.31.1-d28a81d857163a2dd72072634f10eb3977bb3584; Released on: 2020-07-20T23:37:07Z
2020/08/10 16:00:02 [INFO] open api plugin configuration not present at C:\Users\...\AppData\terraform.d\plugins/terraform-provider-openapi.yaml
2020/08/10 16:00:02 [DEBUG] serviceConfig = <nil>
2020/08/10 16:00:02 [ERROR] There was an error initialising the terraform provider: plugin init error: swagger url not provided, please export OTF_VAR_<provider_name>_SWAGGER_URL env variable with the URL where 'openapi' service provider is exposing the swagger file OR create a plugin configuration file at ~/.terraform.d/plugins following the Plugin configuration schema specifications

## To Reproduce
On a Windows 10 machine download and set up a provider.yaml

1. unzip the terraform-provider-openapi 
2. place in correct folder
3. in powershell or cmd run .\terraform-provider-openapi.exe
4. error message follows

**Comment by dikhan** [comment]
Hi @Grasume , thanks for opening the issue.

The error above seems to suggest that the plugin could not find the source of where it should load the OpenAPi document from, which can be provided via the env variable ‘ OTF_VAR_<provider_name>_SWAGGER_URL‘ (where <provider_name> is the name you chose for the plugin eg: terraform-provider-grasume) nor the openapi plugin yaml config file:

`2020/08/10 16:00:02 [ERROR] There was an error initialising the terraform provider: plugin init error: swagger url not provided, please export OTF_VAR_<provider_name>_SWAGGER_URL env variable with the URL where 'openapi' service provider is exposing the swagger file OR create a plugin configuration file at ~/.terraform.d/plugins following the Plugin configuration schema specifications`
- Can you confirm you have a terraform-provider-openapi.yaml file in the C:\Users...\AppData\terraform.d\plugins directory?
- How does your terraform-provider-openapi.yaml config look like? 

You can find more info on how to use the Provider at [Using the OpenAPI Provider](https://github.com/dikhan/terraform-provider-openapi/blob/master/docs/using_openapi_provider.md) documentation.

Thanks,
Dani

**Comment by Grasume** [comment]
@dikhan  sorry for the delay didn't see a response. Yes I have the file in the plugins directory and the terraform-provider-openapi.yaml looks like the below.

`version: '1'
services:
  antsle:
    swagger-url: https://eveinterface.antsle.us/swagger.json
    insecure_skip_verify: true
`

**Comment by Grasume** [comment]
Interestingly when I use $env:OTF_VAR_ANTSLE_SWAGGER_URL="https://eveinterface.antsle.us/swagger.json" before my terraform plan everything works. Im thinking its an issue with how open api is looking for the file here C:\Users...\AppData\terraform.d\plugins/terraform-provider-openapi.yaml but on windows it should be C:\Users...\AppData\terraform.d\plugins\terraform-provider-openapi.yaml

**Comment by dikhan** [comment]
Hi @Grasume ,

Looks like that could very well be the issue. I'd be happy to accept a PR if you would like to provide a fix for that, the code with logic that adds the forward slash lives at https://github.com/dikhan/terraform-provider-openapi/blob/master/openapi/plugin_config.go#L79. You can also refer to the [Contribution guidelines](https://github.com/dikhan/terraform-provider-openapi#contributing) for more info on how to contribute new code.

Thanks!
Dani

**Comment by dikhan** [comment]
Just realized, reading more carefully the details provided on how to reproduce the issue, that the name of the binary does not match the one specified in the `terraform-provider-openapi.yaml`. You need to rename the exe file to be `terraform-provider-antsle.exe`.

Let me know if that works. Also, I tested out on Windows whether having the forward slash in the path (C:\Users...\AppData\terraform.d\plugins/terraform-provider-openapi.yaml) causes any issues and it worked fine, so I think you issue was related to the binary name.

Hope this helps.
Dani

**Comment by dikhan** [comment]
Hi @Grasume ,

Just quickly following up on this, I will go ahead and close off the issue since there’s been no updates since my last reply. Please feel free to reopen the issue if you still have issues or need help.

Thanks,
Dani
