### ISSUE TITLE
Documentation order is non-deterministic

### ISSUE THREAD

**Issue by dogmatic69** [dikhan/terraform-provider-openapi#265]
## Describe the bug
Every time the doc generator is run the resources are in a different order

## To Reproduce
- run doc generator with multiple resources
- view order of generated resources
- repeat and compare results.

## Expected behaviour
Resources should always ben in the same order, perhaps the order they are in the spec file or alphabetical. 

### Checklist (for admin only)

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [ ] I have added a corresponding label (bug) to the issue (right side menu)
- [ ] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)

**Comment by dikhan** [comment]
Hi @dogmatic69 ,

Thanks for opening the issue, I went ahead and added a fix for keeping a deterministic alphabetical order based on the resource and data source names. 

You can check out the new behaviour at #267 

Dani
