### ISSUE TITLE
OpenAPI provider not working

### ISSUE THREAD

**Issue by lordsaibat** [dikhan/terraform-provider-openapi#273]
## Describe the bug
When attempting to use the OpenAPI provider on Windows system, terraform does not identify it. 

## To Reproduce

1. On Windows 10, install the the openapi executable in both:
     - %APPDATA%\terraform.d\plugins
     - C:\hashicorp\  (location of terraform)
2. Configure terraform-provider-openapi.yaml
     - change the services to antserver
3. Copy the openapi executeable to terraform-provider-antserver.exe
4. Verify provider works from code directory
PS C:\Users\.....> terraform-provider-antserver.exe
2020/12/12 06:07:06 Running OpenAPI Terraform Provider v0.31.1-d28a81d857163a2dd72072634f10eb3977bb3584; Released on: 2020-07-20T23:37:07Z
2020/12/12 06:07:06 [INFO] found open api plugin configuration at C:\Users\redacted\AppData\terraform.d\plugins/terraform-provider-openapi.yaml
2020/12/12 06:07:06 [DEBUG] serviceConfig = &{SwaggerURL:https://redacted.antsle.us/swagger.json PluginVersion: InsecureSkipVerify:false SchemaConfigurationV1:[] TelemetryConfig:<nil>}
2020/12/12 06:07:06 [INFO] Provider antserver is using the following swagger file: https://redacted.antsle.us/swagger.json
2020/12/12 06:07:06 [DEBUG] service configuration = &{SwaggerURL:https://redacted.antsle.us/swagger.json PluginVersion: InsecureSkipVerify:false SchemaConfigurationV1:[] TelemetryConfig:<nil>}
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/system/setup/send-esn-token
2020/12/12 06:07:06 [DEBUG] resource path '/api/system/setup/send-esn-token' not terraform compliant: path '/api/system/setup/send-esn-token' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/network/vlans/{vlan-name}/antlets
2020/12/12 06:07:06 [DEBUG] resource path '/api/network/vlans/{vlan-name}/antlets' not terraform compliant: path '/api/network/vlans/{vlan-name}/antlets' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/ads/config
2020/12/12 06:07:06 [DEBUG] resource path '/api/ads/config' not terraform compliant: path '/api/ads/config' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/antlets/{antlet-name}/state
2020/12/12 06:07:06 [DEBUG] resource path '/api/antlets/{antlet-name}/state' not terraform compliant: path '/api/antlets/{antlet-name}/state' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/network/vlans/connect
2020/12/12 06:07:06 [DEBUG] resource path '/api/network/vlans/connect' not terraform compliant: path '/api/network/vlans/connect' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/backups/delete-local-copy
2020/12/12 06:07:06 [DEBUG] resource path '/api/backups/delete-local-copy' not terraform compliant: path '/api/backups/delete-local-copy' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/list-zpools
2020/12/12 06:07:06 [DEBUG] resource path '/api/list-zpools' not terraform compliant: path '/api/list-zpools' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/system/upgrade-edgelinux
2020/12/12 06:07:06 [DEBUG] resource path '/api/system/upgrade-edgelinux' not terraform compliant: path '/api/system/upgrade-edgelinux' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/templates-statuses
2020/12/12 06:07:06 [DEBUG] resource path '/api/templates-statuses' not terraform compliant: path '/api/templates-statuses' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/backups/import-local-backup
2020/12/12 06:07:06 [DEBUG] resource path '/api/backups/import-local-backup' not terraform compliant: path '/api/backups/import-local-backup' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/ads/drive/{name}
2020/12/12 06:07:06 [DEBUG] resource path '/api/ads/drive/{name}' not terraform compliant: resource instance path '/api/ads/drive/{name}' missing required GET operation
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/antlets/{antlet-name}/vusbs/enable
2020/12/12 06:07:06 [DEBUG] resource path '/api/antlets/{antlet-name}/vusbs/enable' not terraform compliant: path '/api/antlets/{antlet-name}/vusbs/enable' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/backups/schedule-backups
2020/12/12 06:07:06 [DEBUG] resource path '/api/backups/schedule-backups' not terraform compliant: path '/api/backups/schedule-backups' is not a resource instance path
2020/12/12 06:07:06 [DEBUG] validating end point terraform compatibility /api/antlets/{antlet-name}
2020/12/12 06:07:06 [DEBUG] resource '/api/antlets/{antlet-name}' root path match: [/api/antlets/{antlet-name} /api/antlets/]
2020/12/12 06:07:06 [DEBUG] found resource root path without trailing '/' - /api/antlets
..........
5. Initialize the terraform project
 terraform.exe init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/antserver...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/antserver: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/antserver

## Expected behaviour
When using terraform init the provider would be picked up and used.
I also attempted $env:OTF_VAR_ANTSLE_SWAGGER_URL="https://<redacted>.antsle.us/swagger.json"

### Checklist (for admin only)

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [ ] I have added a corresponding label (bug) to the issue (right side menu)
- [ ] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)

**Comment by dikhan** [comment]
Hi @lordsaibat ,

Thanks for opening the issue. Can you please confirm what version of Terraform you are using? Looking at the output I am 'guessing' it might be >= Terraform 0.13 which requires the plugins to be installed in a different path. You can find more info on how to install the OpenAPI plugin with Terraform 0.13 [here](https://github.com/dikhan/terraform-provider-openapi/issues/270); the instructions in this repo on how to install this provider are based on [Terraform 0.12 plugin installation instructions)](https://www.terraform.io/docs/plugins/basics.html#installing-plugins).

Please let me know if that helped.
Thanks,
Dani

**Comment by lordsaibat** [comment]
You are correct.

I updated my main.tf to include.

terraform {
  required_providers {
    antserver = {
      source  = "openapi.lan/antsle/antserver"
    }
  }
}

and placed it in every directory I could think of. Here is the output.

terraform init
2020/12/12 12:58:31 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward 
compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/12/12 12:58:31 [INFO] Terraform version: 0.14.2  
2020/12/12 12:58:31 [INFO] Go runtime version: go1.15.2
2020/12/12 12:58:31 [INFO] CLI args: []string{"C:\\hashicorp\\terraform.exe", "init"}
2020/12/12 12:58:31 [DEBUG] Attempting to open CLI config file: C:\Users\redacted\AppData\Roaming\terraform.rc
2020/12/12 12:58:31 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/12/12 12:58:31 [DEBUG] checking for credentials in "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins"   
2020/12/12 12:58:31 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/12/12 12:58:31 [DEBUG] will search for provider plugins in C:\Users\redacted\AppData\Roaming\terraform.d\plugins   
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0" contains invalid type "1.0"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0\\terraform-provider-antserver.exe" contains invalid type "1.0"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0\\terraform-provider-openapi.yaml" contains invalid type "1.0"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.1" contains invalid type "1.1"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.1\\terraform-provider-antserver.exe" contains invalid type "1.1"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.1\\terraform-provider-openapi.yaml" contains invalid type "1.1"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\terraform-provider-antserver.exe" contains invalid type "terraform-provider-antserver.exe"; ignoring       
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\terraform-provider-openapi.yaml" contains invalid type "terraform-provider-openapi.yaml"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\windows_amd64" contains invalid type "windows_amd64"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\windows_amd64\\terraform-provider-antserver.exe" contains invalid type "windows_amd64"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\windows_amd64\\terraform-provider-openapi.yaml" contains invalid type "windows_amd64"; ignoring
2020/12/12 12:58:31 [DEBUG] will search for provider plugins in C:\Users\redacted\AppData\Roaming\HashiCorp\Terraform\plugins

2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.0" contains invalid type "1.0"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.0\\terraform-provider-antserver.exe" contains invalid type "1.0"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.0\\terraform-provider-openapi.yaml" contains invalid type "1.0"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.1" contains invalid type "1.1"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.1\\terraform-provider-antserver.exe" contains invalid type "1.1"; ignoring
Initializ2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.1\\terraform-provider-openapi.yaml" contains invalid type "1.1"; ignoring
i2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\terraform-provider-antserver.exe" contains invalid type "terraform-provider-antserver.exe"; ignoring
2020/12/12 12:58:31 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\terraform-provider-openapi.yaml" contains invalid type "terraform-provider-openapi.yaml"; ignoringn2020/12/12 12:58:31 [INFO] CLI command args: []string{"init"}
g the backen2020/12/12 12:58:31 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
d...  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

2020/12/12 12:58:31 [DEBUG] New state was assigned lineage "517aaf3e-ff2c-f792-6918-72d4f9ee8830"
2020/12/12 12:58:31 [DEBUG] checking for provisioner in "."

2020/12/12 12:58:31 [DEBUG] checking for provisioner in "C:\\hashicorp"
2020/12/12 12:58:31 [DEBUG] checking for provisioner in "C:\\Users\\redated\\AppData\\Roaming\\terraform.d\\plugins"   
2020/12/12 12:58:31 [INFO] Failed to read plugin lock file .terraform\plugins\windows_amd64\lock.json: open .terraform\plugins\windows_amd64\lock.json: The system cannot find the path specified.
2020/12/12 12:58:31 [DEBUG] Service discovery for openapi.lan at https://openapi.lan/.well-known/terraform.json      
Initializing provider plugins...
- Finding latest version of openapi.lan/antsle/antserver...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
openapi.lan/antsle/antserver: could not connect to openapi.lan: Failed to
request discovery document: Get
"https://openapi.lan/.well-known/terraform.json": dial tcp: lookup
openapi.lan: no such host

PS C:\Users\redated\OneDrive\Desktop\Code\.....>

**Comment by dikhan** [comment]
Hi @lordsaibat ,

Based on the log output looks like the path to the plugin may not be the correct one, note that the version must follow semantic versioning and the platform architecture must be set too.

````
"C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan\antsle\1.0\terraform-provider-antserver.exe" contains invalid type "1.0"; ignoring
````

Can you try setting the folders as follows and see if that makes a difference?

````
"C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan\antsle\1.0.0\windows_amd64\terraform-provider-antserver.exe" 
````

The [Terraform implied installation directories](https://www.terraform.io/docs/commands/cli-config.html#implied-local-mirror-directories) contains more details in terms of the default directories that Terraform uses to load the plugins.

**Comment by lordsaibat** [comment]
I tried that but still not working. 

I can copy and paste the locations that it attempts in the output and can call the exe directly.
For example:
C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\windows_amd64\\terraform-provider-antserver.exe 
and it show the provider pulling the correct swigger and everything.

It seems what ever folder or file it loads is an "invalid type".

**Comment by dikhan** [comment]
I believe the error is due to the path missing the **plugin name** AND the **version**. As per [Terraform's in-house-provider instructions](https://www.terraform.io/docs/configuration/provider-requirements.html#in-house-providers) and [Terraform's explicit installation method doc](https://www.terraform.io/docs/commands/cli-config.html#explicit-installation-method-configuration), the unpacked layout format is as follows:

````
Unpacked layout: HOSTNAME/NAMESPACE/TYPE/VERSION/TARGET is a directory containing the result of extracting the provider's distribution zip file.
````

Hence, in your case the path to the provider should look like this:

C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan\antsle\antserver\1.0.0\windows_amd64\terraform-provider-antserver.exe

Where `openapi.lan` would be the hostname, `antsle` the namespace, `antserver` the type (provider name) and `1.0.0` the version of the provider.

You may also want to fix the version used in the terraform configuration like below:

````
terraform {
  required_providers {
    antserver = {
      source = "openapi.lan/antsle/antserver"
      version = "1.0.0"
    }
  }
}
````

**Comment by lordsaibat** [comment]
Ok I updated the provider and create the directory. 
Here is a recursive list of my plugins folder:

```
PS C:\Users\redacted\AppData\Roaming\terraform.d\plugins> Get-ChildItem -Recurse


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2020  12:37 PM                openapi.lan
d-----        12/12/2020  12:40 PM                terraform.example.com
-a----         12/5/2020   4:31 PM       26600960 terraform-provider-antserver.exe
-a----         12/7/2020   6:51 PM             98 terraform-provider-openapi.yaml


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2020   3:05 PM                antsle
-a----         12/5/2020   4:31 PM       26600960 terraform-provider-antserver.exe
-a----         12/7/2020   6:51 PM             98 terraform-provider-openapi.yaml


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan\antsle


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2020  12:37 PM                1.0
d-----        12/12/2020   3:17 PM                1.0.0
d-----        12/12/2020  12:46 PM                1.1
d-----        12/12/2020  12:55 PM                windows_amd64
-a----         12/5/2020   4:31 PM       26600960 terraform-provider-antserver.exe
-a----         12/7/2020   6:51 PM             98 terraform-provider-openapi.yaml


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan\antsle\1.0


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         12/5/2020   4:31 PM       26600960 terraform-provider-antserver.exe
-a----         12/7/2020   6:51 PM             98 terraform-provider-openapi.yaml


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan\antsle\1.0.0


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2020   3:17 PM                windows_amd64
-a----         12/5/2020   4:31 PM       26600960 terraform-provider-antserver.exe
-a----         12/7/2020   6:51 PM             98 terraform-provider-openapi.yaml


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan\antsle\1.0.0\windows_amd64


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         12/5/2020   4:31 PM       26600960 terraform-provider-antserver.exe
-a----         12/7/2020   6:51 PM             98 terraform-provider-openapi.yaml


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan\antsle\1.1


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         12/5/2020   4:31 PM       26600960 terraform-provider-antserver.exe
-a----         12/7/2020   6:51 PM             98 terraform-provider-openapi.yaml


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan\antsle\windows_amd64


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         12/5/2020   4:31 PM       26600960 terraform-provider-antserver.exe
-a----         12/7/2020   6:51 PM             98 terraform-provider-openapi.yaml


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\terraform.example.com


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2020  12:40 PM                examplecorp


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\terraform.example.com\examplecorp


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2020  12:40 PM                ourcloud


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\terraform.example.com\examplecorp\ourcloud


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2020  12:40 PM                1.0.0


    Directory: C:\Users\redacted\AppData\Roaming\terraform.d\plugins\terraform.example.com\examplecorp\ourcloud\1.0.0


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2020  12:40 PM                windows_amd64

```

Here is the output of terraform init now:

```
2020/12/13 07:24:52 [INFO] Terraform version: 0.14.2  
2020/12/13 07:24:52 [INFO] Go runtime version: go1.15.2
2020/12/13 07:24:52 [INFO] CLI args: []string{"C:\\hashicorp\\terraform.exe", "init"}
2020/12/13 07:24:52 [DEBUG] Attempting to open CLI config file: C:\Users\redacted\AppData\Roaming\terraform.rc
2020/12/13 07:24:52 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/12/13 07:24:52 [DEBUG] checking for credentials in "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins"
2020/12/13 07:24:52 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/12/13 07:24:52 [DEBUG] will search for provider plugins in C:\Users\redacted\AppData\Roaming\terraform.d\plugins
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0" contains invalid type "1.0"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0\\terraform-provider-antserver.exe" contains invalid type "1.0"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0\\terraform-provider-openapi.yaml" contains invalid type "1.0"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0.0" contains invalid type "1.0.0"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0.0\\terraform-provider-antserver.exe" contains invalid type "1.0.0"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0.0\\terraform-provider-openapi.yaml" contains invalid type "1.0.0"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0.0\\windows_amd64" contains invalid type "1.0.0"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0.0\\windows_amd64\\terraform-provider-antserver.exe" contains invalid type "1.0.0"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.0.0\\windows_amd64\\terraform-provider-openapi.yaml" contains invalid type "1.0.0"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.1" contains invalid type "1.1"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.1\\terraform-provider-antserver.exe" contains invalid type "1.1"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\1.1\\terraform-provider-openapi.yaml" contains invalid type "1.1"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\terraform-provider-antserver.exe" contains invalid type "terraform-provider-antserver.exe"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\terraform-provider-openapi.yaml" contains invalid type "terraform-provider-openapi.yaml"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\windows_amd64" contains invalid type "windows_amd64"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\windows_amd64\\terraform-provider-antserver.exe" contains invalid type "windows_amd64"; ignoring
2020/12/13 07:24:52 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins\\openapi.lan\\antsle\\windows_amd64\\terraform-provider-openapi.yaml" contains invalid type "windows_amd64"; ignoring
2020/12/13 07:24:52 [DEBUG] will search for provider plugins in C:\Users\redacted\AppData\Roaming\HashiCorp\Terraform\plugins
2020/12/13 07:24:53 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.0" contains invalid type "1.0"; ignoring
2020/12/13 07:24:53 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.0\\terraform-provider-antserver.exe" contains invalid type "1.0"; ignoring
2020/12/13 07:24:53 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.0\\terraform-provider-openapi.yaml" contains invalid type "1.0"; ignoring
2020/12/13 07:24:53 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.1" contains invalid type "1.1"; ignoring
2020/12/13 07:24:53 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.1\\terraform-provider-antserver.exe" contains invalid type "1.1"; ignoring
l provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\1.1\\terraform-provider-openapi.yaml" contains invalid type "1.1"; ignoring
2020/12/13 07:24:53 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\terraform-provider-antserver.exe" contains invalid type "terraform-provider-antserver.exe"; ignoring
2020/12/13 07:24:53 [WARN] local provider path "C:\\Users\\redacted\\AppData\\Roaming\\Hashicorp\\Terraform\\plugins\\openapi.lan\\antsle\\terraform-provider-openapi.yaml" contains invalid type "terraform-provider-openapi.yaml"; ignoring
2020/12/13 07:24:53 [INFO] CLI command args: []string{"init"}
2020/12/13 07:24:53 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/12/13 07:24:53 [DEBUG] New state was assigned lineage "e15e6f40-cbef-5b05-1268-c94974405075"
2020/12/13 07:24:53 [DEBUG] checking for provisioner in "."
2020/12/13 07:24:53 [DEBUG] checking for provisioner in "C:\\hashicorp"
2020/12/13 07:24:53 [DEBUG] checking for provisioner in "C:\\Users\\redacted\\AppData\\Roaming\\terraform.d\\plugins"
2020/12/13 07:24:53 [INFO] Failed to read plugin lock file .terraform\plugins\windows_amd64\lock.json: open .terraform\plugins\windows_amd64\lock.json: The system cannot find the path specified.
2020/12/13 07:24:53 [DEBUG] Service discovery for openapi.lan at https://openapi.lan/.well-known/terraform.json
```

**Comment by dikhan** [comment]
I don't see the `C:\Users\redacted\AppData\Roaming\terraform.d\plugins\openapi.lan\antsle\antserver\1.0.0\windows_amd64\terraform-provider-antserver.exe` in the above list.

**Comment by lordsaibat** [comment]
Alright that was the key. Man that was painful.
Thanks for all the help.
