### ISSUE TITLE
Error running terraform plan in the examples_container

### ISSUE THREAD

**Issue by maneeshsahu** [dikhan/terraform-provider-openapi#293]
## Describe the bug
I get an `Error: Invalid version constraint` when running `terraform plan` in the examples_container.

## To Reproduce
A clear and concise description on how does it work now and what's the current behaviour.

1. Make the `examples_container` target 
2. In the interactive terminal `cd goa`
3. Run terraform init and terraform plan

Get an error about a version constraint:

```
Error: Invalid version constraint

  on main.tf line 3, in terraform:
   3:     goa = {
   4:       source  = "terraform.example.com/examplecorp/goa"
   5:       version = ">= 2.0.0"
   6:     }

A string value is required for goa.
```

## Expected behaviour
An error free terraform plan.

## Additional context
In the docker container, the terraform version is `Terraform v0.12.0`

### Checklist (for admin only)

**Don't forget to go through the checklist to make sure the issue is created properly**:

- [x] I have added a corresponding label (bug) to the issue (right side menu)
- [x] I have added this issue to the 'API Terraform Provider' GitHub project (right side menu)

**Comment by dikhan** [comment]
Hey @maneeshsahu ,

Thanks for raising the issue, I just submitted a new PR that should be fixing it. Can you take a look at it and let me know if it solves the issue?

https://github.com/dikhan/terraform-provider-openapi/pull/294

Thanks!
Dani

**Comment by maneeshsahu** [comment]
Works in the branch `293-fix-docker-examples`
