### ISSUE TITLE
InternalValidate Error on "-" character in swagger.json

### ISSUE THREAD

**Issue by bradthebuilder** [dikhan/terraform-provider-openapi#305]
## Describe the bug
`terraform validate` fails when the terraform-provider-openapi binary walks [my service provider's](https://docs.antsle.com/system/using-the-antman-rest-api-with-terraform) swagger.json file. It asks me to file a bug report: "Internal validation of the provider failed! This is always a bug with the provider itself, and not a user issue. Please report this bug"

## To Reproduce
I'm attempting to use [Terraform 1.0.0](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-1-0-general-availability) and this [project's 2.0.6 release](https://github.com/dikhan/terraform-provider-openapi/releases/tag/v2.0.6) together with my service provider's API. I'm attempting to use[ local provider mirroring](https://www.terraform.io/docs/cli/config/config-file.html#explicit-installation-method-configuration) so that I can have multiple terraform projects pull the terraform-provider-openapi from my local disk at `terraform init` time.

1. Create a terraform project directory: `mkdir test`
2. Put `provider.tf` and `main.tf` in this directory
Contents of provider.tf:
```
terraform {
  required_providers {
    antsle = {
      source = "localhost/antsle/antsle"
      version = "~> 1.0.0"
    }
  }
}

variable "apikey_auth" {
  default = "Token ey"
}

provider "antsle" {
  api_key = var.apikey_auth
}

```
Contents of main.tf:
```
resource "antsle_antlets" "antlet1" {
  dname       = "antlet"
  template    = "debian"
  ram         = 1024
  cpu         = 1
  antlet_num  = 33
  zpool_name  = "antlets"
  compression = "lz4"
}
```
3. Put the following in your ~/.terraformrc file, replacing my name with your home directory name:
```
provider_installation {
   filesystem_mirror {
     path    = "/home/brad/.local/share/terraform/plugins/"
     include = ["localhost/*/*"]
   }
}
```
4. Put the 2.0.6 release binary renamed to `terraform-provider-antsle` and the `terraform-provider-openapi.yaml` files into `~/.local/share/terraform/plugins/localhost/antsle/antsle/1.0.0/linux_amd64/`
Contents of `~/.local/share/terraform/plugins/localhost/antsle/antsle/1.0.0/linux_amd64/terraform-provider-openapi.yaml`:
```
version: 1
services:
    antsle:
      swagger-url: https://cscijoy.antsle.us/swagger.json
```
5. Back in your `test` directory, run `terraform init`. This succeeds; the .terraformrc and provider.tf work together to symlink the project directory's `.terraform/providers/localhost/antsle/antsle/1.0.0/linux_amd64` to `~/.local/share/terraform/plugins/localhost/antsle/antsle/1.0.0/linux_amd64`.
6. Finally, run `terraform validate` or `terraform plan`. The error occurs here.

## Expected behaviour
`terraform validate` does not crash.

## Additional context
I ran `export TF_LOG=TRACE` before running `terraform validate` to [generate some logs](https://gist.github.com/bradthebuilder/f3c3ccfdc6f7b037d63bd30c0c622f90). The error message is all the way down at the bottom. My take-away from scrutinizing this is that the four main terraform-compatible APIs that are mapped to Antsle resources are successfully found and registered with the provider binary, but the `managed-origin` string in the `swagger.json` causes the openapi provider binary to hiccup. It looks like it tries to convert the dash character into an underscore in the output, but something maybe just goes wrong in that process.

Without access to an Antsle device (and it's swagger.json), I don't expect this to be easy to re-create for anyone on the team, but I'm more than willing to run tests and collaborate if this is believed to be a bug with this provider. If I'm mistaken and this is a lack of robustness of the service provider's API (I.E. their problem), please feel free to close this issue. The URL for the swagger.json is for my Antsle device on my local network, and I don't think the software's terms of service/EULA will allow me to share all of it. Screenshots provided along with [logs gist](https://gist.github.com/bradthebuilder/f3c3ccfdc6f7b037d63bd30c0c622f90) to help make sense of the problem.

![Bug](https://user-images.githubusercontent.com/49787611/123350726-92e83900-d529-11eb-982c-cae04e870d86.png)
![antsle_managed-origin](https://user-images.githubusercontent.com/49787611/123350762-a85d6300-d529-11eb-93c2-b81015beaf58.png)

**Comment by dikhan** [comment]
Hi @bradthebuilder , as far as I can see in the logs the issue is that the definition property name contain characters that are currently not compatible with terraform naming convention (eg: colons). The OpenApI terraform provider attempts 

resource antsle_antlets: antsle:managed_origin: Field name may only
[31m│[0m [0mcontain lowercase alphanumeric characters & underscores.

**Comment by bradthebuilder** [comment]
Thanks a ton @dikhan for taking a look-see. I completely eye-grepped over that! I'll share this with the service provider to see if they'd be interested in adding this into their backlog. Case closed =)

**Comment by dikhan** [comment]
Hey @bradthebuilder , sorry I saved my comment too early while I was still typing the response. Please take a look again at my reply just in case you did not see the full reply.
